"""Operator-readable Markdown report."""
from __future__ import annotations

from io import StringIO

from phishprint.scan import Report

_SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}


def to_markdown(report: Report) -> str:
    out = StringIO()
    p = lambda s="": out.write(s + "\n")  # noqa: E731

    p(f"# phishprint report — `{report.domain}`")
    p()
    p(f"_Generated by phishprint v{report.tool_version}._")
    p()

    # ---- Score ----------------------------------------------------------
    p("## Readiness")
    p()
    p(f"**Score:** {report.score.total} / 100  —  **Band:** {report.score.band}")
    p()
    p("| Component | Points |")
    p("| --- | ---: |")
    for k, v in report.score.components.items():
        p(f"| {k} | {v} |")
    p()

    # ---- MX -------------------------------------------------------------
    p("## MX")
    p()
    if report.mx.error:
        p(f"_Error:_ {report.mx.error}")
    elif not report.mx.hosts:
        p("_No MX records published._")
    else:
        p("| Pref | Hostname | IPs | ASN |")
        p("| ---: | --- | --- | --- |")
        for h in report.mx.hosts:
            ips = ", ".join(h.ips) if h.ips else "—"
            asn = f"AS{h.asn} {h.asn_org}" if h.asn else "—"
            p(f"| {h.preference} | `{h.hostname}` | {ips} | {asn} |")
    p()

    # ---- SPF ------------------------------------------------------------
    p("## SPF")
    p()
    if not report.spf.present:
        p("_No SPF record._")
    else:
        p(f"**Record:** `{report.spf.record}`")
        p()
        p(f"- Terminal: `{report.spf.all_qualifier or '(missing)'}` ({report.spf.strictness})")
        p(f"- DNS lookups: {report.spf.lookup_count} (limit 10)")
        p(f"- Status: **{report.spf.status}**")
        if report.spf.includes:
            p(f"- Includes: {', '.join('`' + i + '`' for i in report.spf.includes)}")
        if report.spf.errors:
            p("- Errors:")
            for e in report.spf.errors:
                p(f"  - {e}")
    p()

    # ---- DMARC ----------------------------------------------------------
    p("## DMARC")
    p()
    if not report.dmarc.present:
        p("_No DMARC record._")
    else:
        d = report.dmarc
        p(f"**Record:** `{d.record}`")
        p()
        p(f"- Policy: `p={d.policy}`  Subdomain: `sp={d.sub_policy or '(inherits p)'}`")
        p(f"- Coverage: pct={d.pct}")
        p(f"- Alignment: adkim=`{d.adkim}` aspf=`{d.aspf}`")
        if d.rua:
            p(f"- rua: {', '.join('`' + a + '`' for a in d.rua)}")
        if d.ruf:
            p(f"- ruf: {', '.join('`' + a + '`' for a in d.ruf)}")
    p()

    # ---- DKIM -----------------------------------------------------------
    p("## DKIM")
    p()
    p(f"_Tried {report.dkim.selectors_tried} selectors._")
    p()
    if not report.dkim.found:
        p("No selectors observable via wordlist (does not prove absence).")
    else:
        p("| Selector | Key type | State |")
        p("| --- | --- | --- |")
        for s in report.dkim.found:
            state = "revoked (p=)" if s.revoked else ("present" if s.has_public_key else "no key")
            p(f"| `{s.selector}` | {s.key_type or '—'} | {state} |")
    p()

    # ---- Auxiliary ------------------------------------------------------
    p("## Auxiliary")
    p()
    p(f"- BIMI: {'present' if report.bimi.present else 'absent'}"
      + (f" (VMC: `{report.bimi.vmc}`)" if report.bimi.vmc else ""))
    p(f"- MTA-STS: {'published (TXT only — policy not fetched)' if report.mta_sts.present else 'absent'}")
    p(f"- TLS-RPT: {'present' if report.tls_rpt.present else 'absent'}"
      + (f" (rua: `{report.tls_rpt.rua}`)" if report.tls_rpt.rua else ""))
    p()

    # ---- Vendors --------------------------------------------------------
    p("## Vendor fingerprint")
    p()
    if not report.vendors:
        p("_No vendors matched._")
    else:
        p("| Vendor | Category | Inspection | Confidence | Evidence |")
        p("| --- | --- | --- | --- | --- |")
        for v in report.vendors:
            ev = "; ".join(f"{e.kind}=`{e.matched}`" for e in v.evidence)
            p(f"| {v.name} | {v.category} | {v.inspection} | {v.confidence} | {ev} |")
    p()

    # ---- Findings -------------------------------------------------------
    p("## Bypass conditions")
    p()
    if not report.findings:
        p("_None detected._")
    else:
        for f in sorted(report.findings, key=lambda x: _SEVERITY_ORDER.get(x.severity, 99)):
            p(f"### [{f.severity.upper()}] {f.title}")
            p()
            p(f.detail)
            p()

    # ---- Recommendations ------------------------------------------------
    p("## Recommendations")
    p()
    for r in report.recommendations:
        p(f"### {r.topic}")
        p()
        p(r.guidance)
        p()

    p("---")
    p("_Authorized use only. phishprint performs passive DNS reconnaissance; "
      "operators are responsible for engagement scope and authorization._")
    return out.getvalue()
